export const FETCH_DISCOVER_PAGE_REQUEST = 'FETCH_DISCOVER_PAGE_REQUEST';
export const FETCH_DISCOVER_PAGE_FAILURE = 'FETCH_DISCOVER_PAGE_FAILURE';
export const FETCH_DISCOVER_PAGE_SUCCESS = 'FETCH_DISCOVER_PAGE_SUCCESS';
