export const PLAYER_LOAD_EPISODE_DATA = 'PLAYER_LOAD_EPISODE_DATA';
export const PLAYER_CAN_PLAY_THROUGH = 'PLAYER_CAN_PLAY_THROUGH';
export const PLAYER_PLAY = 'PLAYER_PLAY';
export const PLAYER_PAUSE = 'PLAYER_PAUSE';
export const PLAYER_UPDATE_TIME = 'PLAYER_UPDATE_TIME';
