export const FETCH_PODCAST_PAGE_REQUEST = 'FETCH_PODCAST_PAGE_REQUEST';
export const FETCH_PODCAST_PAGE_FAILURE = 'FETCH_PODCAST_PAGE_FAILURE';
export const FETCH_PODCAST_PAGE_SUCCESS = 'FETCH_PODCAST_PAGE_SUCCESS';
