export const FETCH_PODCASTS_REQUEST = 'FETCH_PODCASTS_REQUEST';
export const FETCH_PODCASTS_FAILURE = 'FETCH_PODCASTS_FAILURE';
export const FETCH_PODCASTS_SUCCESS = 'FETCH_PODCASTS_SUCCESS';
export const CLEAR_SEARCH_TERM = 'CLEAR_SEARCH_TERM';
